### ISSUE TITLE
[Cloud-TST] loggedin as dwp-mgmt, trying to assign a candidate to a position and in that screen identified below issues.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#198]
1) As i logged in as DWP-MGMT user, but below screen is referring multiple accounts.,
2) whey 'NAAN' is displaying, - Can some help us on how to get a valid value here.,
![image](https://user-images.githubusercontent.com/24892801/93887899-2fea1d00-fcdf-11ea-82af-0bf36cf7c908.png)

**Comment by Adharshd** [comment]
@ to be discussed in scrum call.

**Comment by rashmidevapura** [comment]
Fixed Naan issue

**Comment by rashmidevapura** [comment]
Account fix assigning to Rajesh

**Comment by rkulkar5** [comment]
As discussed in the call please make the changes so as to display the client field in the UI only if the candidate belongs to DWP account

**Comment by ranjeetibm** [comment]
Fixed. Code checked-in to GIT and today night it will be deployed to cloud. 
Please retest after the deployment.

**Comment by Tatireddysreevani** [comment]
still getting multiple accounts in client dropdown
![image](https://user-images.githubusercontent.com/61975055/94689852-fe132f00-034c-11eb-86c6-23f14e9df217.png)

**Comment by ranjeetibm** [comment]
As discussed. Please retest.

**Comment by Tatireddysreevani** [comment]
No Ranjeet, not getting still

**Comment by Tatireddysreevani** [comment]
working as per requirement
