### ISSUE TITLE
Account level sme and Partner- Getting warning message "we noticed that you attempted to move away from this tab/browser during exam" in partner and sme queue

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#206]
when we moved to some other browser from sme or partner queue, it is showing warning message of "we noticed that you attempted to move away from this tab/browser during exam. Please retain from doing so still you finish the exam" even when we are not in assessment screen.
![image](https://user-images.githubusercontent.com/61975055/94136415-8b084500-fe82-11ea-9081-2df9434d7c34.png)

**Comment by Adharshd** [comment]
Should happen only in the quiz. Assigned to @Adharshd

**Comment by Tatireddysreevani** [comment]
Its happening when we are in sme, partner queue and moved to some other tab/browser

**Comment by Adharshd** [comment]
@Teja-swi Please test again when the code is deployed in cloud.

**Comment by Adharshd** [comment]
Made some more changes - please retest after next cloud deployment if its not working currently. @Tatireddysreevani

**Comment by Tatireddysreevani** [comment]
sure Adharsh

**Comment by Tatireddysreevani** [comment]
closing as working fine

**Comment by Tatireddysreevani** [comment]
Again we are getting error message in admin screen, sme and partner screen
![Screenshot_2020-10-08-10-47-21-338_com android chrome](https://user-images.githubusercontent.com/61975055/95420792-c19d8f80-0959-11eb-9c34-c990bcbd3b53.jpg)

**Comment by ranjeetibm** [comment]
Issue fixed. Please retest once code is  deployed to cloud.

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/97415946-d3a49980-192b-11eb-8ca1-88efa5454f5b.png)
still getting same warning message. we are getting this warning message when we move to another browser but not getting when we move to another tab

**Comment by ranjeetibm** [comment]
Hi, 
Could you please provide the step to replicate this. I did the testing as per your suggestion and am not getting the warning message. Followed below step:
1. opened Mozilla and Logged-in the tool with candidate credential
1. finished candidate exam and landed on pre-tecnical form page. clicked on next tab..NO warning message.
2. Logout pre technical form page and clicked on next page. No warning message
2. opened chrome for another browser - No warning message

**Comment by Tatireddysreevani** [comment]
Hi,
These are the steps i had followed while testing:
1. Opened Mozilla and logged in to tool with DWPAdmin credentials, then created candidate "dwpcan3@in.ibm.com"
2. Logged in with candidate credentials and attempted quiz. While attempting quiz, moved to chrome and again came to Mozilla, that time i got warning message(this is as per requirement). 
3.clicked on pre technical form, while filling pre technical form i moved to another browser(chrome) and again came to Mozilla..... i got warning message here also.

**Comment by Teja-swi** [comment]
@ranjeetibm 

The alert seems to appear when there are no adequate questions in question bank. SInce Samir is showing the alert message 'no enough questions' after clicking the START EXAM button, system is treating this as exam has started.


![image](https://user-images.githubusercontent.com/66815529/97540857-3ceae200-19ea-11eb-9112-5b5bf5c2db7d.png)

![image](https://user-images.githubusercontent.com/66815529/97540530-c8b03e80-19e9-11eb-84d5-3323c6a848a2.png)

**Comment by ranjeetibm** [comment]
Hi.
I have fixed the issue pointed by Tejaswi for the warning alert after "Insufficient question.." message. Please restest once code is deployment to cloud.

Also, in today's scrum call Sreevani updated that previous issues for this incident is working fine now. So please close the incident after today's issue testing.

Thanks,

**Comment by Teja-swi** [comment]
Hi Ranjeet, Latest code is deployed one hour ago and I still see this issue.

**Comment by ranjeetibm** [comment]
As discussed, please retest and if all good please close the defect.
