### ISSUE TITLE
Delete/Edit of questions once appered in online assessment

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#255]
Admin should be able to edit the questions that once appeared in the online assessment. It should not effect ' candidate assessment details' and the prior question will be soft deleted from the list as per the discussion.

**Comment by deekshanagesh08** [comment]
Issue is fixed. Kindly test once deployed on cloud

**Comment by Teja-swi** [comment]
Hi,

Tried the same for Contractor, Given quiz for 10 questions, But Candidate assessment detail is showing 20 questions.

![image](https://user-images.githubusercontent.com/66815529/97956061-b6f5df00-1dcd-11eb-8abd-a4eb4460deea.png)

![image](https://user-images.githubusercontent.com/66815529/97956109-d987f800-1dcd-11eb-8762-43a4ea41a9a7.png)


![image](https://user-images.githubusercontent.com/66815529/97956096-cf65f980-1dcd-11eb-868f-c73c884ebc46.png)

**Comment by Teja-swi** [comment]
After a re-test
I have observed below for candidate assessment details
**before updating questions**
Regular employee - No  issue
contractor - there is some issue

**after updating questions**
Regular employee - there is some issue
contractor - there is some issue

**Comment by deekshanagesh08** [comment]
Fixed, test once deployed on cloud

**Comment by Teja-swi** [comment]
Hi Deeksha,

I can still see this issue, 
![image](https://user-images.githubusercontent.com/66815529/98233219-b8b5d300-1f84-11eb-8b9d-64f187e67ae1.png)

**Comment by Teja-swi** [comment]
Hi Deeksha,

I have edited questions  -----> on quiz I am getting edited questions.
Later, I edited questions again ---> But not getting edited questions

![image](https://user-images.githubusercontent.com/66815529/98650754-56334d00-235f-11eb-985c-909114553e61.png)

![image](https://user-images.githubusercontent.com/66815529/98650802-677c5980-235f-11eb-88bd-b68a2afd4c76.png)

**Comment by deekshanagesh08** [comment]
Issue is fixed. Test once deployed on cloud

**Comment by Tatireddysreevani** [comment]
now we are getting edited questions in quiz
![image](https://user-images.githubusercontent.com/61975055/99379639-f30d6180-28ee-11eb-93ae-d00831e4a8ce.png)

But if we gave 20 questions in test configuration, then the percentage calculation going wrong. Here i answered 18 questions correctly and 2 wrongly. Then percentage would be 90%, but here its showing 55%. And here it is showing you have correctly answered 11 questions out of 20
![image](https://user-images.githubusercontent.com/61975055/99379836-2ea82b80-28ef-11eb-987d-6fb2edac551a.png)
![image](https://user-images.githubusercontent.com/61975055/99379899-42539200-28ef-11eb-843d-9787e21a4640.png)
![image](https://user-images.githubusercontent.com/61975055/99379965-5bf4d980-28ef-11eb-96db-0588591048d2.png)
![image](https://user-images.githubusercontent.com/61975055/99380191-9f4f4800-28ef-11eb-9fb3-48e49dc8a975.png)
![image](https://user-images.githubusercontent.com/61975055/99380245-b0985480-28ef-11eb-883b-8ed15c6e8b56.png)
![image](https://user-images.githubusercontent.com/61975055/99380288-c148ca80-28ef-11eb-8809-24545414a92e.png)
![image](https://user-images.githubusercontent.com/61975055/99380356-d6bdf480-28ef-11eb-97d2-708e865d6926.png)
![image](https://user-images.githubusercontent.com/61975055/99380400-e89f9780-28ef-11eb-8ad1-ab1e3a3f8e54.png)

**Comment by Teja-swi** [comment]
SInce issue is similar to that of issue 293 , closing this issue
