### ISSUE TITLE
JRSS - Create candidate

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#267]
Currently, while creating candidate..Job role will load only if test is configured.  If for a particular JRSS , if online assessment is skipped and no test configuration available  ...it should display in the drop down of create Candidate.

![image](https://user-images.githubusercontent.com/66815529/96696471-6ed7c500-13a8-11eb-8b25-70c5e3dd161d.png)

![image](https://user-images.githubusercontent.com/66815529/96696692-ad6d7f80-13a8-11eb-9474-669b5f33761a.png)

**Comment by rkulkar5** [comment]
Fixed

**Comment by Teja-swi** [comment]
Hi Rajesh,

I issue still exists in cloud. Can you please re-check.

**Comment by rkulkar5** [comment]
I have checked on cloud its working as expected
Steps followed
1) logged in as single account admin (RKDWPAdmin@in.ibm.com/Password@123)
2) Created a new JRSS
3) mapped the JRSS with technology stream
4) configured the workflow, skip Online Technical Assessment 
5) Navigate to create candidate screen and was able to see the new JRSS created in the dropdown

**Comment by Teja-swi** [comment]
Issue fixed.
