### ISSUE TITLE
Edit - Test Configuration

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#283]
Please go through the  screenshots below. Able to update Test Configuration to a JRSS & Account which were logically not mapped.

![image](https://user-images.githubusercontent.com/66815529/97702657-5fa5f500-1ad5-11eb-8ba8-eef668a46ae7.png)

Please note Jobe role is empty here.
![image](https://user-images.githubusercontent.com/66815529/97702748-7fd5b400-1ad5-11eb-8336-4069469aa9b7.png)

![image](https://user-images.githubusercontent.com/66815529/97702781-911ec080-1ad5-11eb-9199-96a9172c2ffe.png)

**Comment by rashmidevapura** [comment]
Fixed please test once deployed on the cloud

**Comment by Tatireddysreevani** [comment]
fixed....

**Comment by Tatireddysreevani** [comment]
still facing same issue
for DWP account "java technical assessment" job role mapped.
for NHS account "manger" job role mapped.
![image](https://user-images.githubusercontent.com/61975055/97846814-9289fc00-1d14-11eb-8ed2-0a1f5b007136.png)
here i am trying to update test configuration for manager and changed account to DWP and no job role selected
![image](https://user-images.githubusercontent.com/61975055/97846930-c2390400-1d14-11eb-9a3e-cba084462172.png)
but updated  to DWP account in which "manager" job role were not mapped
![image](https://user-images.githubusercontent.com/61975055/97846977-dd0b7880-1d14-11eb-94b6-fe551a75fa6d.png)

**Comment by rashmidevapura** [comment]
Fixed the issue..please test once deployed in cloud

**Comment by rashmidevapura** [comment]
By accidently checked in the passing score validation on edit, checked in back. please test once deployment happens.

**Comment by Tatireddysreevani** [comment]
Sure Rashmi, will check and inform

**Comment by Tatireddysreevani** [comment]
closing as working fine
