### ISSUE TITLE
Search filter- Multi Admin Screen

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#337]
In Test results of Multi admin screen,  account filter is not working
![image](https://user-images.githubusercontent.com/61975055/102453619-996d9380-4062-11eb-8435-6d6a1a8e5029.png)

**Comment by rashmidevapura** [comment]
Fixed and please test once deployed

**Comment by Tatireddysreevani** [comment]
Still facing the same issue
![image](https://user-images.githubusercontent.com/61975055/102772071-ed52e200-43ac-11eb-87da-970e07de8838.png)

**Comment by Tatireddysreevani** [comment]
issue fixed
![image](https://user-images.githubusercontent.com/61975055/102876701-96601200-446b-11eb-9bab-3a10bf75a510.png)
